# Author: Jens Bruno Wittek

# contains additional custom expressions to complete the R style of NppToR (for Notepad++)
# of course, not all are included (only the ones I used yet), but anyway about 700 altogether


# instruction words
# actually package names. putting them as "instruction words" allows to visualise them differently, however, put them where you prefer
agricolae animation asbio birk bstats car CircStats ctv e1071 fmsb foreign formatR gap Hmisc installr knitr lattice lavaan leaps lme4 lmtest lsr MASS mgcv mnormt multilevel MVN nlme nnet psych Rfacebook sandwich spdep splines TeachingDemos tseries vcd wordcloud XML
#
# base words
AIC alpha ani.options ani.pause Anova Arg as.array as.character as.complex as.data.frame as.Date as.dendrogram as.difftime as.double as.factor as.integer as.list as.logical as.matrix as.null as.numeric as.ordered as.pairlist as.POSIXct as.POSIXlt as.raster as.single as.vector assocstats bar bartlett.test BIC binom.test bptest browseEnv cell2nb chisq.test chooseCRANmirror chow.test close.screen coeftest col2rgb colMeans colorRampPalette colSums Conj conv_unit convertColor cor.test cordif cortest.bartlett cov2cor cramersV create.bspline.basis data.frame debugonce describe dev.copy dev.cur dev.list dev.next dev.off dev.prev dev.set DH.test dice dir.create dmnorm do.call download.file dwtest etaSquared expand.grid extractAIC fa fa.parallel file.append file.choose file.copy file.create file.exists file.info file.remove file.rename fisher.test fitted.values frac fractions friedman.test gam gam.check getbasismatrix getPage getPost getRversion gls GmeanRel graph.ran.mean graphics.off help.search help.start HoltWinters HT.test I ICC1 ICC2 Im ineq install.packages install.views installed.packages interaction.plot invIrM IQR is.array is.character is.complex is.data.frame is.dendrogram is.double is.factor is.finite is.function is.infinite is.integer is.list is.logical is.matrix is.na is.nan is.null is.numeric is.ordered is.pairlist is.symmetric.nb is.vector jarque.bera.test kde2d KMO knit knit_theme knit2pdf kruskal.test ks.test kurtosis lag.listw lam lda LETTERS leveneTest linear.hypothesis linearHypotheses list.files lm.ridge lme lmer lockBinding log10 log2 logLik lrtest LSD.test mantelhaen.test mardia.test mauchly.test Mod model.matrix month.abb month.name moran.mc moran.plot moran.test multinom na.omit NagelkerkeR2 nb2listw nb2mat new.env new.packages nlevel old.packages opts_chunk p.adjust packageDescription packageVersion pairs.panels pairwise.t.test partial.r paste0 phtest plm plm.data plot.density plot.dice plot.ts pmnorm pp.plot principal proc.time prop.test purl rasterImage Re read.csv read.delim read.dta read.fwf read.gal read.gwt2nb read.spss read.table readLines readPNG recordPlot replayPlot rgb2hsv rmnorm rowMeans rowSums royston.test RSiteSearch s save.image scatterplot3d sem set set.seed setdir sigma.test skewness smc smooth.spline smoothScatter split.screen spweights.constants state.abb state.name summary.manova symbol Sys.Date Sys.sleep Sys.time Sys.timezone system.file system.time t.test te tidy_source tidy.opts tilde TukeyHSD unzip update.packages update.views var.test VarCorr vcovHC View vif vis.gam waba waldtest which.max which.min white.test wilcox.test within write.csv write.foreign write.table xmlRoot xmlSApply xmlTreeParse
#
# keywords
add adj alternative ann arrow ask at axes base bg blank bootci breaks bty byrow center cex cex.axis cex.lab cex.main cex.sub col.axis color cond conf.level convert.underscore CorrB CorrW crt dec device dfB dfW digits direction each encoding envir expand expr factors fg file1 file2 fileEncoding first fm font freq from fun FUN group header height highlight.3d horiz horizontal imaginary indent index INDEX INDICES interval lab label lambda las last length.out level list.len listw location lower ltheta lty lwd main mar MARGIN maxColorValue maximum meanlog method mfrow model n.ahead na.action na.strings names.arg nderiv newdata nfactors nint norder nreps oma origin outline override.id p.adj package parameter pattern pch phi pin plot.it plot.type pointsize pos post prob probability probs random randomisation rate recursive ref region.id replacement res rho right rot.per rotate rotation row.names rsquare scipen scope sdlog se select sep shade shape shape1 shape2 side sigma Sigma size skip srt standardized tck test theta ticktype times to to.data.frame token too.far torus type units upper value varcov vertical what width widths words xaxs xaxt xlab xlim xpd Y.names yaxs ylab ylim
#